# .rubocop.yml

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineHashBraceLayout:
  EnforcedStyle: symmetrical

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: symmetrical

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
